service: ListingSecurityGroups
frameworkVersion: ">=1.0.0 <2.0.0"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  region: us-east-1
  endpointType: REGIONAL
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:Describe*"
      Resource:
        - "*"
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 1
      rateLimit: 1

functions:
  list:
    handler: handler.list
    description: List all security groups of an AWS account
    events:
      - http:
          path: /list
          method: get
          cors: true
