service: ListingSecurityGroups
frameworkVersion: ">=1.0.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  endpointType: REGIONAL
  timeout: 900
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
      Resource:
        - "*"

functions:
  list:
    handler: handler.list
    description: List all security groups of an AWS account
    timeout: 900
    events:
      - http:
          path: /list
          method: get
          cors: true
